- reload formatting
Changed files:
    tenshi.init -> 1.6

diff --git a/tenshi.init b/tenshi.init
--- a/tenshi.init
+++ b/tenshi.init
@@ -59,11 +59,12 @@ case "$1" in
   reload|force-reload)
 	if [ -f /var/lock/subsys/tenshi ]; then
 		if checkconfig; then
-			show "Reloading tenshi configuration and flushing all queues"; echo
+			show "Reloading tenshi configuration and flushing all queues"
 			kill -HUP `cat /var/run/tenshi/tenshi.pid`
 			RETVAL=$?
+			[ $RETVAL = 0 ] && ok || fail
 		else
-			show "tenshi config file has syntax error, not restarting"; echo
+			show "The tenshi config file has syntax error, not restarting"; fail
 			RETVAL=7
 		fi
 	else
